# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ec2-service-catalog-terraform-state"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "af-south-1"
  }
}
