AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Linux 3 EC2 Instance with Dynatrace ActiveGate'

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge

  InstanceName:
    Type: String
    Default: service-catalog-instance
    Description: Name for the EC2 instance

  Environment:
    Type: String
    Default: dev
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod

  KeyPairName:
    Type: String
    Default: ""
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance

  VpcId:
    Type: String
    Default: ""
    Description: VPC ID where the instance will be launched

  SubnetId:
    Type: String
    Default: ""
    Description: Subnet ID where the instance will be launched

  IamInstanceRole:
    Type: String
    Default: ""
    Description: IAM instance profile name to attach to the EC2 instance

Resources:
  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-005718719f185fb3e
      InstanceType: !Ref InstanceType
      KeyName: !If [HasKeyPairName, !Ref KeyPairName, !Ref AWS::NoValue]
      SubnetId: !If [HasSubnetId, !Ref SubnetId, !Ref AWS::NoValue]
      IamInstanceProfile: !If [HasIamInstanceRole, !Ref IamInstanceRole, !Ref AWS::NoValue]
      # Security groups will be attached via Service Action

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          yum update -y
          
          # Install required packages
          yum install -y curl wget jq
          
          # Install CloudWatch Agent
          yum install -y amazon-cloudwatch-agent
          
          # Configure CloudWatch Agent
          cat > /opt/aws/amazon-cloudwatch-agent/bin/config.json << 'EOF'
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "cwagent"
            },
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/messages",
                      "log_group_name": "/aws/ec2/${InstanceName}/messages",
                      "log_stream_name": "{instance_id}"
                    },
                    {
                      "file_path": "/var/log/secure",
                      "log_group_name": "/aws/ec2/${InstanceName}/secure",
                      "log_stream_name": "{instance_id}"
                    }
                  ]
                }
              }
            },
            "metrics": {
              "metrics_collected": {
                "disk": {
                  "measurement": ["used_percent"],
                  "metrics_collection_interval": 60,
                  "resources": ["*"]
                },
                "mem": {
                  "measurement": ["mem_used_percent"],
                  "metrics_collection_interval": 60
                }
              }
            }
          }
          EOF
          
          # Start CloudWatch Agent
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
          systemctl enable amazon-cloudwatch-agent
          systemctl start amazon-cloudwatch-agent
          
          # Tag the instance
          INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          aws ec2 create-tags --resources $INSTANCE_ID --tags \
            Key=Name,Value=${InstanceName} \
            Key=Environment,Value=${Environment} \
            Key=ManagedBy,Value=CloudFormation
          
          echo "EC2 instance setup completed successfully"
      Tags:
        - Key: Name
          Value: !Ref InstanceName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

Conditions:
  HasKeyPairName: !Not [!Equals [!Ref KeyPairName, ""]]
  HasVpcId: !Not [!Equals [!Ref VpcId, ""]]
  HasSubnetId: !Not [!Equals [!Ref SubnetId, ""]]
  HasIamInstanceRole: !Not [!Equals [!Ref IamInstanceRole, ""]]


Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref EC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"

  InstancePublicIP:
    Description: Public IP address of the created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-InstancePublicIP"

  InstancePrivateIP:
    Description: Private IP address of the created EC2 instance
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: !Sub "${AWS::StackName}-InstancePrivateIP"

  CloudformationStackARN:
    Description: ARN of the CloudFormation stack
    Value: !Ref AWS::StackId
    Export:
      Name: !Sub "${AWS::StackName}-StackARN" 